name: psv_to_kml_converter
description: Конвертер PSV файлов в KML с отображением на карте

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Для работы с картами
  flutter_map: ^6.1.0
  latlong2: ^0.8.1
  
  # Для получения файлов через share menu
  receive_sharing_intent: ^1.4.5
  
  # Для работы с файлами
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  file_picker: ^6.1.1
  
  # Для сохранения и экспорта файлов
  share_plus: ^7.2.1
  
  # UI компоненты
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  
  # Утилиты
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
